AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  langchain_daily_job_summary_agent

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  ModerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HttpApi:
          Type: Api
          Properties:
            Path: /summarize
            Method: post
        DailySchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 20 ? * MON-FRI *)
            Name: DailySummarySchedule
            Description: "Runs daily job summary at 8PM on weekdays"
            Input: !Sub |
              {
                "date": "${!format('YYYY-MM-DD')}"
              }
      Environment:
        Variables:
          OPENAI_API_KEY: '{{resolve:ssm:/prod/openai/api-key:1}}'
          DEFAULT_OPEN_AI_MODEL: '{{resolve:ssm:/prod/openai/model:1}}'
          DEFAULT_TEMPERATURE: '{{resolve:ssm:/prod/openai/temperature:1}}'
          DEFAULT_MAX_TOKENS: '{{resolve:ssm:/prod/openai/max-tokens:1}}'
          TAVILY_API_KEY: '{{resolve:ssm:/prod/tavily/api-key:1}}'
          SLACK_USER_TOKEN: '{{resolve:ssm:/prod/slack/user-token:1}}'
          GOOGLE_CREDENTIALS_PATH: '{{resolve:ssm:/prod/google/credentials-path:1}}'
          GOOGLE_DELEGATED_USER: '{{resolve:ssm:/prod/google/delegated-user:1}}'

Outputs:
  SummarizerApi:
    Description: "API Gateway endpoint URL for Prod stage for Daily Job Summarizer"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summarize"
